name: MarioNette
channels:
- pytorch
- defaults
dependencies:
- jupyter=1.0.0
- pytorch=1.7.1
- torchvision=0.8.2
- pip:
  - absl-py==0.11.0
  - cachetools==4.2.1
  - chardet==4.0.0
  - coloredlogs==15.0
  - cycler==0.10.0
  - google-auth==1.24.0
  - google-auth-oauthlib==0.4.2
  - grpcio==1.35.0
  - humanfriendly==9.1
  - idna==2.10
  - imageio==2.9.0
  - imageio-ffmpeg==0.4.3
  - jedi==0.17.2
  - joblib==1.0.0
  - jsonpatch==1.28
  - jsonpointer==2.0
  - kiwisolver==1.3.1
  - markdown==3.3.3
  - matplotlib==3.3.4
  - oauthlib==3.1.0
  - pandas==1.2.1
  - parso==0.7.1
  - pluggy==0.13.1
  - protobuf==3.14.0
  - pyaml==20.4.0
  - pyasn1==0.4.8
  - pyasn1-modules==0.2.8
  - python-jsonrpc-server==0.4.0
  - python-language-server==0.36.2
  - pytz==2020.5
  - pyyaml==5.4.1
  - requests==2.25.1
  - requests-oauthlib==1.3.0
  - rsa==4.7
  - scikit-learn==0.24.1
  - scipy==1.6.0
  - seaborn==0.11.1
  - sqlalchemy==1.3.22
  - tensorboard==2.4.1
  - tensorboard-plugin-wit==1.8.0
  - threadpoolctl==2.1.0
  - torch-tools==0.1.5
  - torchfile==0.1.0
  - tqdm==4.56.0
  - ujson==4.0.2
  - urllib3==1.26.3
  - visdom==0.1.8.9
  - websocket-client==0.57.0
  - werkzeug==1.0.1
